### ISSUE TITLE
An error occurred while I was running.

### ISSUE THREAD

**Issue by Nvpiao** [polyaxon/traceml#11]
//******************************************************************************************
X, y = generate_data(sin_cos, np.linspace(0, 100, 10000), TIMESTEPS, seperate=False)

validation_monitor = learn.monitors.ValidationMonitor(X['val'], y['val'],
                                                      every_n_steps=PRINT_STEPS,
                                                      early_stopping_rounds=1000)
regressor.fit(X['train'], y['train'], 
              monitors=[validation_monitor], 
              batch_size=BATCH_SIZE,
              steps=TRAINING_STEPS)

//*****************************************************************************************
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:Setting feature info to TensorSignature(dtype=tf.float64, shape=TensorShape([Dimension(None), Dimension(5), Dimension(2)]), is_sparse=False)
WARNING:tensorflow:Setting targets info to TensorSignature(dtype=tf.float64, shape=TensorShape([Dimension(None), Dimension(2)]), is_sparse=False)

---

TypeError                                 Traceback (most recent call last)
<ipython-input-4-673e90bf8d3c> in <module>()
      7               monitors=[validation_monitor],
      8               batch_size=BATCH_SIZE,
----> 9               steps=TRAINING_STEPS)

/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.pyc in fit(self, x, y, input_fn, steps, batch_size, monitors, max_steps)
    330                              steps=steps,
    331                              monitors=monitors,
--> 332                              max_steps=max_steps)
    333     logging.info('Loss for final step: %s.', loss)
    334     return self

/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.pyc in _train_model(self, input_fn, steps, feed_fn, init_op, init_feed_fn, init_fn, device_fn, monitors, log_every_steps, fail_on_nan_loss, max_steps)
    648       features, targets = input_fn()
    649       self._check_inputs(features, targets)
--> 650       train_op, loss_op = self._get_train_ops(features, targets)
    651 
    652       # Add default monitors.

/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.pyc in _get_train_ops(self, features, targets)
    936       Tuple of train `Operation` and loss `Tensor`.
    937     """
--> 938     _, loss, train_op = self._call_model_fn(features, targets, ModeKeys.TRAIN)
    939     return train_op, loss
    940 

/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.pyc in _call_model_fn(self, features, targets, mode)
    920       else:
    921         return self._model_fn(features, targets, mode=mode)
--> 922     return self._model_fn(features, targets)
    923 
    924   def _get_train_ops(self, features, targets):

/home/nvpiao/tensorflow/pm25/code/tensorflow-lstm-regression-master/lstm.py in _lstm_model(X, y)
    106         stacked_lstm = tf.nn.rnn_cell.MultiRNNCell(lstm_cells(rnn_layers), state_is_tuple=True)
    107         x_ = tf.unpack(X, axis=1, num=num_units)
--> 108         output, layers = tf.nn.rnn(stacked_lstm, x_, dtype=dtypes.float32)
    109         output = dnn_layers(output[-1], dense_layers)
    110         prediction, loss = learn.models.linear_regression(output, y)

/usr/lib/python2.7/site-packages/tensorflow/python/ops/rnn.pyc in rnn(cell, inputs, initial_state, dtype, sequence_length, scope)
    214             state_size=cell.state_size)
    215       else:
--> 216         (output, state) = call_cell()
    217 
    218       outputs.append(output)

/usr/lib/python2.7/site-packages/tensorflow/python/ops/rnn.pyc in <lambda>()
    201       if time > 0: varscope.reuse_variables()
    202       # pylint: disable=cell-var-from-loop
--> 203       call_cell = lambda: cell(input_, state)
    204       # pylint: enable=cell-var-from-loop
    205       if sequence_length is not None:

/usr/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell.pyc in **call**(self, inputs, state, scope)
    811                 state, [0, cur_state_pos], [-1, cell.state_size])
    812             cur_state_pos += cell.state_size
--> 813           cur_inp, new_state = cell(cur_inp, cur_state)
    814           new_states.append(new_state)
    815     new_states = (tuple(new_states) if self._state_is_tuple

/usr/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell.pyc in **call**(self, inputs, state, scope)
    308       else:
    309         c, h = array_ops.split(1, 2, state)
--> 310       concat = _linear([inputs, h], 4 \* self._num_units, True)
    311 
    312       # i = input_gate, j = new_input, f = forget_gate, o = output_gate

/usr/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell.pyc in _linear(args, output_size, bias, bias_start, scope)
    905       res = math_ops.matmul(args[0], matrix)
    906     else:
--> 907       res = math_ops.matmul(array_ops.concat(1, args), matrix)
    908     if not bias:
    909       return res

/usr/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.pyc in concat(concat_dim, values, name)
    799   return gen_array_ops._concat(concat_dim=concat_dim,
    800                                values=values,
--> 801                                name=name)
    802 
    803 

/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.pyc in _concat(concat_dim, values, name)
    412   """
    413   result = _op_def_lib.apply_op("Concat", concat_dim=concat_dim,
--> 414                                 values=values, name=name)
    415   return result
    416 

/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.pyc in apply_op(self, op_type_name, name, **keywords)
    461                                 (prefix, dtype.name))
    462               else:
--> 463                 raise TypeError("%s that don't all match." % prefix)
    464             else:
    465               raise TypeError("%s that are invalid." % prefix)

TypeError: Tensors in list passed to 'values' of 'Concat' Op have types [float64, float32] that don't all match.
//******************************************************************************************************

if i write like this 

 X, y = generate_data(sin_cos, np.linspace(0, 100, 10000, dtype=tf.float32), TIMESTEPS, seperate=False)

i will get this

---

TypeError                                 Traceback (most recent call last)
<ipython-input-5-6ed65a6a40d6> in <module>()
----> 1 X, y = generate_data(sin_cos, np.linspace(0, 100, 10000, dtype=tf.float32), TIMESTEPS, seperate=False)
      2 # create a lstm instance and validation monitor
      3 validation_monitor = learn.monitors.ValidationMonitor(X['val'], y['val'],
      4                                                       every_n_steps=PRINT_STEPS,
      5                                                       early_stopping_rounds=1000)

/usr/lib64/python2.7/site-packages/numpy/core/function_base.pyc in linspace(start, stop, num, endpoint, retstep, dtype)
    123         return y.astype(dtype, copy=False), step
    124     else:
--> 125         return y.astype(dtype, copy=False)
    126 
    127 

TypeError: data type not understood

how can i fix it.
thanks for help.
sorry for my poor english

**Comment by claytantor** [comment]
this is happening to me also on this example: https://github.com/mouradmourafiq/tensorflow-lstm-regression/blob/master/lstm_sin.ipynb
