### ISSUE TITLE
update example to tf 1.0.0

### ISSUE THREAD

**Issue by tfzxyinhao** [polyaxon/traceml#23]
The latest version tensorflow is 1.0.0
rnn_cell was moved to tensorflow.contrib
i am beginner for tensorflow,can you update exmaple to the latest version of tensorflow ?

**Comment by zhuojimmy** [comment]
I update lstm.py and lstm-weather.ipynb to Tensorflow 1.0.0 in my repositories .
Tensorflow 1.0.0 . Python 3.5.2 . Run on Windows.
https://github.com/zhuojimmy/tensorflow-lstm-regression
(我为什么要用英语呢)

**Comment by nadavb** [comment]
Even with the new version (zhuojimmy) I get:
tensorflow.python.ops.nn has no attribute rnn_cell

**Comment by nadavb** [comment]
@zhuojimmy, I get:

TypeError                                 Traceback (most recent call last)
<ipython-input-6-298cf2e95fd0> in <module>()
      1 predicted = regressor.predict(X['test'])
----> 2 rmse = np.sqrt(((predicted - y['test']) ** 2).mean(axis=0))
      3 score = mean_squared_error(predicted, y['test'])
      4 print ("MSE: %f" % score)

TypeError: unsupported operand type(s) for -: 'generator' and 'float'

**Comment by mouradmourafiq** [comment]
I update the code to use tensorflow-1.1.0, but not the original code, I am currently using a library called [polyaxon](https://github.com/polyaxon/polyaxon/).

**Comment by fengjiqiang-git** [comment]
@nadavb ,
add the **`predicted = np.array(list(predicted))`**
